### ISSUE TITLE
The pack struct not use in json message format.

### ISSUE THREAD

**Issue by youzio** [mainflux/senml#4]
Hello, as I see the SenML use  ' []senml.Record', not use 'senml.Pack', I found the definition of senml.Pack below:

// Pack consists of SenML records array.
type Pack struct {
	XMLName *bool    `json:"_,omitempty" xml:"sensml"`
	Xmlns   string   `json:"_,omitempty" xml:"xmlns,attr"`
	**Records []Record `xml:"senml"`**
}
Why not use this struct's json-Marshal?

**Comment by dusanb94** [comment]
As per https://tools.ietf.org/html/rfc8428#section-5: `The root JSON value consists of an array with one JSON object for each SenML Record.`
