### ISSUE TITLE
Allow SenML without Value in Base Record in line with RFC 8428 spec

### ISSUE THREAD

**Issue by wmkamerman** [mainflux/senml#6]
According to the RFC 8428 spec, it seems to be valid to not have a Value in the Base Record of a JSON SenML record. Please see [Section 5.1.7](https://datatracker.ietf.org/doc/html/rfc8428#section-5.1.7), first example. However, the Mainflux SenML transformer requires a Value field to be present in each SenML Record.

Meaning the following SenML is invalid according to Mainflux:

```
[
  {
    "bn": "urn:dev:ow:10e2073a01080063:",
    "bt": 1648560975
  },
  {
    "n": "temperature",
    "u": "Cel",
    "v": 18.3
  },
  {
    "n": "humidity",
    "u": "%RH",
    "v": 42
  }
]
```

But this is valid (first and second Records are merged):

```
[
  {
    "bn": "urn:dev:ow:10e2073a01080063:",
    "bt": 1648560975,
    "n": "temperature",
    "u": "Cel",
    "v": 18.3
  },
  {
    "n": "humidity",
    "u": "%RH",
    "v": 42
  }
]
```

You can see in the following `Validate` function that an `ErrNoValues` is thrown if a Value is not present:
https://github.com/mainflux/senml/blob/78a09af66021636e0974f768118d54a9674ed7ff/senml.go#L230-L232

Can you update the Mainflux SenML Validator to be in line with the RFC 8428 spec?

**Comment by dusanb94** [comment]
This design is driven by the spec, [Section 4.2](https://datatracker.ietf.org/doc/html/rfc8428#section-4.2):

>    Value:  Value of the entry.  Optional if a Sum value is present;
      otherwise, it's required.  Values are represented using basic data
      types.  This specification defines floating-point numbers ("v"
      field for "Value"), booleans ("vb" for "Boolean Value"), strings
      ("vs" for "String Value"), and binary data ("vd" for "Data
      Value").  Exactly one Value field MUST appear unless there is a
      Sum field, in which case it is allowed to have no Value field.

The particular example from the spec, however, does not have any of the `sum value`, `base value`, or any of the `value` fields. It looks to me that's the only such example.

**Comment by wmkamerman** [comment]
Hi @dusanb94, thank you for responding! If I understand you correctly, this particular example in the spec is incorrect? In that case I will have to contact the third party that is sending data to us. 

Or would it be possible to allow a base Record without a Value using some flag?

**Comment by dusanb94** [comment]
Hello, @wmkamerman, you're welcome. TBH, I can't be sure if the example is incorrect or the spec, but it looks like the example to me. Spec is very precise and this is the only example that does not meet requirements.

> Or would it be possible to allow a base Record without a Value using some flag?

It would definitely be possible, but I would not like to do that because 1) the doc per se does not specify validation is configurable and 2) it looks to me that the spec is correct, it's just the example that isn't. Is it possible for the data provider to modify packets? Also, you can contact the original spec authors to check if the example is wrong, or I can write them an email.

**Comment by wmkamerman** [comment]
Thank you! I have contacted the data provider to see if they can modify their packets, but this will surely take time if they even will do this at all. I will contact the spec authors :)

**Comment by dusanb94** [comment]
Thanks, @wmkamerman. Please keep us posted if we should update, it's really a simple task, as you mentioned.

**Comment by wmkamerman** [comment]
@dusanb94 I have an update from the spec authors. You are right: the example in the spec is wrong, and very record needs to have a value or a sum.

> Thank you for your email and indeed finding an error in the example of the SenML specification.
>  
> During the standardization work in the CoRE WG we discussed for some time whether the first record could have "only base values" and eventually we concluded that the benefits of allowing that are smaller than the downsides. Hence the RFC says you must always have either value or sum. Seems that we missed to update one of the examples and we should file an errata on the RFC to make that clear.

We can close this issue - I will reach out to our data provider.

**Comment by dusanb94** [comment]
@wmkamerman Thanks for the explanation.
